feat(deps): Use cachetools v5
carta/flipper-client pull request #53
Opened 2023-04-12 14:45 UTC by antoinelafouasse

This change allows consumers to switch to a higher version of cachetools; fortunately there are no breaking changes in cachetools that impact this library.

See cachetools changelog: https://github.com/tkem/cachetools/blob/master/CHANGELOG.rst

2023-04-12 18:22 UTC, adambom requested changes

2023-04-12 18:22 UTC, adambom commented on setup.py
> +    "cachetools~=5.3.0",
We can make this a bit more permissive if we express the dependency requirement as a range. That way if someone really wants to run version 4, they can still opt in to doing that.

```suggestion
    "cachetools>=4.2.1,<6"
```

2023-04-19 21:15 UTC, adambom approved these changes
Looks good. Would you mind bumping the version to `1.3.2` and I'll release this.

2023-04-20 07:55 UTC, antoinelafouasse commented
> Looks good. Would you mind bumping the version to `1.3.2` and I'll release this.

Done, thanks for your support 🙇‍♂️

2023-04-20 17:24 UTC, adambom approved these changes

2023-04-20 17:24 UTC, merged

2023-04-20 17:24 UTC, adambom commented
Thanks for your contribution. This will be available in PyPi shortly.